# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'Azure Pipelines'
#  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'OptumHackathonPipelineConnection'
    subscriptionId: '5f9408a9-1889-41f0-8c06-f3c880e19c6a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'OptumHackathon-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/manikumar446/OptumHackathon/main/template.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
    addSpnToEnvironment: true
